# Generated by Django 6.0.3 on 2026-04-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-collected_at'], 'verbose_name': 'Price History', 'verbose_name_plural': 'Price Histories'},
        ),
        migrations.AlterModelOptions(
            name='trackingitems',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tracking Item', 'verbose_name_plural': 'Tracking Items'},
        ),
    ]
