# Generated by Django 6.0.3 on 2026-04-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrules',
            options={'verbose_name': 'Custom Rule', 'verbose_name_plural': 'Custom Rules'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
