# Generated by Django 6.0.3 on 2026-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customrules_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrules',
            name='custom_rule',
        ),
        migrations.AddField(
            model_name='customrules',
            name='notify_back_in_stock',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о появлении в наличии'),
        ),
        migrations.AddField(
            model_name='customrules',
            name='notify_price_drop',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о снижении цены'),
        ),
        migrations.AddField(
            model_name='customrules',
            name='notify_weekly_summary',
            field=models.BooleanField(default=False, verbose_name='Еженедельная сводка'),
        ),
    ]
